# Generated by Django 5.1.3 on 2025-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='status',
        ),
    ]
