# Generated by Django 5.1.3 on 2025-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('recurring_transaction', '0003_alter_recurringtransaction_category_and_more'),
        ('saving_plan', '0008_delete_deadlineextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='savings_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='saving_plan.savingsplan'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='category.category'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10),
        ),
    ]
