# Generated by Django 5.1.3 on 2025-02-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsplan',
            name='status',
        ),
    ]
