# Generated by Django 5.1.3 on 2025-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0002_remove_savingsplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
