# Generated by Django 5.1.3 on 2025-02-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0003_savingsplan_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='savings_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_transactions', to='saving_plan.savingsplan'),
        ),
    ]
