# Generated by Django 5.1.3 on 2025-02-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0004_alter_savingstransaction_savings_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsTransaction',
        ),
    ]
