# Generated by Django 5.1.3 on 2025-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0005_delete_savingstransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsplan',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='priority',
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10),
            preserve_default=False,
        ),
    ]
