# Generated by Django 5.1.3 on 2025-02-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plan', '0007_alter_savingsplan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeadlineExtension',
        ),
    ]
